package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"
	"encoding/json"
	"go-graphql-api/database"
	"go-graphql-api/graph/model"
	"go-graphql-api/logs_logic"
)

// GetUser is the resolver for the GetUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*model.User, error) {
	//var user model.User
	var Os_log logs_logic.Simple_log
	Os_log.Message = "Попытка получить пользователя - "

	user, err := database.GetUserFromDB(id)
	var val []byte
	val, _ = json.Marshal(user)
	Os_log.Answer = string(val[:])
	if err != nil {
		Os_log.Message = Os_log.Message + "Ошибка"
	} else {
		Os_log.Message = Os_log.Message + "Успех"
	}
	Os_log.Query_id = id
	Os_log.Query_type = "GetUser"
	logs_logic.Write_usual_log(Os_log)

	return user, err
	//panic(fmt.Errorf("not implemented: GetUser - GetUser"))
}

// GetTransaction is the resolver for the GetTransaction field.
func (r *queryResolver) GetTransaction(ctx context.Context, id string) (*model.Transaction, error) {
	trans, err := database.GetTransFromDB(id)
	return trans, err
	//panic(fmt.Errorf("not implemented: GetTransaction - GetTransaction"))
}

// GetGood is the resolver for the GetGood field.
func (r *queryResolver) GetGood(ctx context.Context, id string) (*model.Good, error) {
	good, err := database.GetGoodFromDB(id)
	return good, err
	//panic(fmt.Errorf("not implemented: GetGood - GetGood"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
